### ISSUE TITLE
Release zfec 1.5.4

### ISSUE THREAD

**Issue by sajith** [tahoe-lafs/zfec#30]
Uploading wheel packages to the Python Package Index would be useful.

This checklist should help:

- [x] Prepare wheel and sdist packages: done in #20.
- [x] Upload packages to test.pypi.org: [done](https://test.pypi.org/project/zfec/1.5.4/).
- [x] Test against Tahoe-LAFS CI: done in tahoe-lafs/tahoe-lafs/pull/804.
- [x] Add Python 3.8 to list of languages: done in #25.
- [x] Other minor tweaks: #18, #23, #24.
- [x] Update NEWS and Changelog: in #29.
- [ ] Tag `zfec-1.5.4`, and wait for cibuildwheel to do its thing.
- [ ] Upload zfec-1.5.4 wheel and sdist packages to PyPI.
- [ ] Freak out, and wait for someone to yell about something or the other breaking.

Related:
- [ ] Update Tahoe-LAFS CI configuration: remove vcpython27 installation step.
